  - name: copying service to catalogue
    ansible.builtin.template:
     src: catalogue.service.j2
     dest: /etc/systemd/system/catalogue.service

  - name: Reload catalogue service
    ansible.builtin.systemd_service:
     daemon_reload: true

  - name: enable and start catalogue service
    ansible.builtin.service:
     name: catalogue 
     state: started
     enabled: yes